---
ID: "dbdd3aec-0f3c-4537-adcf-61348240bae9"
Parent: "4415e38e-b7c3-48ec-9070-dca80de71158"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Habitat Sites/Habitat Home Raspberry/gulp/tasks/watchAll
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/DBDD3AEC0F3C4537ADCF61348240BAE9.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "66b556a7-43f1-4157-bc57-5ad5cb34aabf"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KaW1wb3J0IGZzIGZyb20gJ2ZzJzsNCi8vDQppbXBvcnQgbG9naW4gZnJvbSAnLi9sb2dpbic7DQoNCg0KZ3VscC50YXNrKCdhbGwtd2F0Y2gnLCBbJ2xvZ2luJ10sDQogICAgZnVuY3Rpb24oKSB7DQogICAgICAgIGdsb2JhbC5pc1dhdGNoaW5nID0gdHJ1ZTsNCiAgICAgICAgZ3VscC5ydW4oJ3Nhc3Mtd2F0Y2gnKQ0KICAgICAgICBndWxwLnJ1bignanMtd2F0Y2gnKQ0KICAgICAgICBndWxwLnJ1bignY3NzLXdhdGNoJykNCiAgICAgICAgZ3VscC5ydW4oJ2ltZy13YXRjaCcpDQogICAgICAgIGd1bHAucnVuKCd3YXRjaC1zb3VyY2Utc2FzcycpDQogICAgICAgIGd1bHAucnVuKCdodG1sLXdhdGNoJykNCiAgICB9KQ0KDQpndWxwLnRhc2soJ2RlZmF1bHQnLCBbJ2FsbC13YXRjaCddKQ==
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 478
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180223T050234Z
